# 更新后的extract_objects.py
import datetime
import re
import sys
import math
from pathlib import Path

# 正则表达式匹配宏调用
PATTERN = r'REGISTER_OBJECT\s*\(\s*"([^"]+)"\s*,\s*[^)]+\)'

def sanitize_macro_name(s):
    """将字符串转换为合法的大写宏名称"""
    # 保留字母数字和下划线，其他字符转下划线，并转为大写
    s = re.sub(r'[^a-zA-Z0-9_]', '_', s)
    return f'ID_{s.upper()}'

def generate_ids(strings) -> str:
    header = ""

    # 添加每个字符串的宏定义
    seen = set()
    i = 1
    for s in strings:
        if s in seen:
            print(f"Warning: Duplicate string '{s}' will be skipped")
            continue

        progress = f"{math.ceil(i / len(strings) * 100)}%"
        progress = progress.rjust(4)

        print(f"[{progress}]: Generating id for '{s}'")
        seen.add(s)
        i = i + 1
        
        macro_name = sanitize_macro_name(s)
        header += f'    constexpr static const char {macro_name}[] = "{s}";\n'
    return header


def generate_header(strings, output_path):
    """生成C++头文件"""
    header = f'''// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by {Path(__file__).name}
// Regenerated on: {datetime.datetime.now().isoformat()}

#pragma once
#ifndef _REGISTERED_IDS_H_
#define _REGISTERED_IDS_H_

#define OBJ_R (store::RegisteredIds)

namespace store {{

class RegisteredIds {{
public:

{generate_ids(strings)}
}};
}}

#endif // _REGISTERED_IDS_H_

'''


    Path(output_path).parent.mkdir(exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header)

if __name__ == "__main__":
    output_file = sys.argv[1]
    input_files = sys.argv[2:]
    
    print(">>>> Generating object ids... >>>>")   

    all_strings = []
    for f in input_files:
        with open(f, 'r', encoding='utf-8') as src:
            content = src.read()
            all_strings.extend(re.findall(PATTERN, content, re.DOTALL))
    
    generate_header(all_strings, output_file)

    print("<<<< Done <<<<")
