// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by generator_registed_id.py
// Regenerated on: 2025-04-11T14:25:07.112656

#pragma once
#ifndef _REGISTERED_IDS_H_
#define _REGISTERED_IDS_H_

#define OBJ_R (store::RegisteredIds)

namespace store {

class RegisteredIds {
public:

    constexpr static const char ID_MAIN_WINDOW[] = "main_window";
    constexpr static const char ID_LE_NUM[] = "le_num";
    constexpr static const char ID_LABEL_NUM[] = "label_num";

};
}

#endif // _REGISTERED_IDS_H_

