// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by generator_registed_id.py
// Regenerated on: 2026-04-17T15:59:32.285186

#pragma once
#ifndef _REGISTERED_IDS_H_
#define _REGISTERED_IDS_H_

#define OBJ_R (store::RegisteredIds)

namespace store {

class RegisteredIds {
public:


};
}

#endif // _REGISTERED_IDS_H_

