// AUTO-GENERATED FILE - DO NOT EDIT
// This file was automatically generated by generator_registed_id.py
// Regenerated on: 2025-04-11T13:30:20.395056

#pragma once
#ifndef _REGISTERED_IDS_H_
#define _REGISTERED_IDS_H_

#define R (store::RegisteredIds)

namespace store {

class RegisteredIds {
public:

    constexpr static const char ID_MAIN_WINDOW[] = "main_window";

};
}

#endif // _REGISTERED_IDS_H_

